artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1ArZQhYChicOaM2AFE7dj0FNDzQPwBW7L/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_save_path: artifacts/prepare_base_model/base_model.pth
  update_base_model_path: artifacts/prepare_base_model/update_base_model.pth


train_model:
  root_dir: artifacts/train_model
  model_save_path: artifacts/train_model/model.pth

model_inference:
  root_dir: artifacts/model_inference
  source_url: https://drive.google.com/file/d/1wDxN-Fmsd3oGFJT2a__38iK_gtJfhFSo/view?usp=sharing
  local_model_file: artifacts/model_inference/model.pth
  model_dir: artifacts/model_inference


